 
<h3>Listar Funcionário</h3>

<table>
    <tr>
        <th>NOME</th>
        <th>CPF</th>
        <th>SALÁRIO</th>
        <th>EDITAR</th>
        <th>EXCLUIR</th>
    </tr>
    <?php foreach ($this->lista as $f):
        ?>
        <tr>
            <td><?php echo $f->getNome(); ?></td>
            <td><?php echo $f->getCpf(); ?></td>
            <td><?php echo $f->getSalario(); ?></td>
            <td>Editar</td>
            <td>Excluir</td>
        </tr>
    <?php endforeach; ?>
</table>
<a href="<?php echo $this->url('home'); ?>">Voltar</a>

