<h3>Adicionar Funcionário</h3>
<form method="post">
    Informe o nome do funcionário..:
    <br> 
    <input type="text" name="nome"> 
    <br><br>
    Informe o cpf do funcionário..: 
    <br> 
    <input type="text" name="cpf"> 
    <br>
    <br>Email<br>    
    <input type="text" name="email"> 
    <br><br>
    Informe o Password
    <br>
    <input type="password" name="password"> 
    <br><br>
    <input type="submit" value="Adicionar"> 

</form> 
<a href="<?php echo $this->url('sonuser-listar', array('controller' => 'index', 'action' => 'listar')); ?>">Listar Funcionario</a> 

<br><br>
<?php echo $this->resp; ?>

